/* Generated by tools/generate_body_stabilization_config.py. Do not edit. */
#ifndef BODY_STABILIZATION_CONFIG_H
#define BODY_STABILIZATION_CONFIG_H
#include "body_stabilizer.h"
#define BODY_STABILIZATION_CONFIG_SHA256 "e1f929e79154f07af1f205feadaa091437ecf3ea66d6740b5368ae57a61a3483"
static const BodyStabilizerConfig BODY_STABILIZATION_DEFAULT_CONFIG = {
    .target_roll_rad = 0.0f,
    .target_pitch_rad = 0.0f,
    .kp_roll = 0.1f,
    .kp_pitch = 0.1f,
    .kd_roll_s = 0.01f,
    .kd_pitch_s = 0.01f,
    .angle_alpha = 0.5f,
    .gyro_alpha = 0.2f,
    .max_roll_rad = 0.05f,
    .max_pitch_rad = 0.05f,
    .max_foot_offset_m = 0.005f,
    .max_error_rad = 0.1745329252f,
    .max_gyro_rad_s = 3.141592654f,
    .timeout_ms = 100U,
    .slew_rad_s = 0.15f,
    .stance_transition_s = 0.08f,
};
static inline BodyStabilizerConfig body_stabilizer_default_config(void) {
    return BODY_STABILIZATION_DEFAULT_CONFIG;
}
#endif
