/* Generated by tools/generate_locomotion_profiles.py. Do not edit. */
#ifndef LOCOMOTION_PROFILES_H
#define LOCOMOTION_PROFILES_H
#define LOCOMOTION_MANIFEST_SHA256 "810d04975b5fb81b6181ef18ee9fb7c157d18ac023fd1cd97697745f7eb5650c"
#define LOCOMOTION_PROFILE_COUNT 12
#define LOCOMOTION_DEFAULT_PROFILE 2
static const char *const locomotion_names[] = {"legacy","crawl","cruise","trot","highstep","lift","imu","level","level15","joint","jointfast","jointsport"};
static const float locomotion_parameters[12][2][7] = {
  {{0},{0}},
  {{1.4f,0.8f,0.05f,0.012f,0.20175f,-0.035f,1.5f},{1.4f,0.8f,0.05f,0.012f,0.20175f,-0.035f,1.5f}},
  {{1.05f,0.6f,0.08f,0.012f,0.20175f,-0.035f,0.75f},{1.05f,0.6f,0.08f,0.012f,0.20175f,-0.035f,0.75f}},
  {{0.8436922562f,0.5979488438f,0.06280689762f,0.012f,0.2017522828f,-0.035f,0.7411947428f},{0.8436922562f,0.5979488438f,0.06280689762f,0.012f,0.2017522828f,-0.035f,0.7411947428f}},
  {{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f},{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f}},
  {{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f},{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f}},
  {{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f},{1.05f,0.6f,0.045f,0.02f,0.20175f,-0.035f,0.75f}},
  {{1.0f,0.64f,0.065f,0.007f,0.20175f,-0.035f,0.75f},{1.05f,0.6f,0.08f,0.012f,0.20175f,-0.035f,0.75f}},
  {{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f},{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f}},
  {{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f},{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f}},
  {{1.5f,0.64f,0.085f,0.015f,0.20175f,-0.035f,0.75f},{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f}},
  {{1.5f,0.59f,0.105f,0.015f,0.20175f,-0.035f,0.75f},{1.4f,0.64f,0.065f,0.015f,0.20175f,-0.035f,0.75f}},
};
static const float locomotion_joint_lead_s[LOCOMOTION_PROFILE_COUNT][3] = {
  {0,0,0},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.0f,0.0f},
  {0.0f,0.04f,0.01f},
  {0.0f,0.04f,0.01f},
  {0.0f,0.04f,0.01f},
};
static const float locomotion_turn_lift_m[LOCOMOTION_PROFILE_COUNT] = {
  0.0f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0000000000f,
  0.0250000000f,
};
static const float locomotion_turn_posture_m[LOCOMOTION_PROFILE_COUNT][2] = {
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.0f,0.0f},
  {0.24f,-0.01f},
};
#endif
