"""Export V6.2.1 periodic support without duplicating the CAD or V6.1 table."""
if __package__ in (None, ''):
    import sys
    from pathlib import Path
    sys.path.insert(0,str(Path(__file__).resolve().parents[4]))
import argparse
import json
from pathlib import Path
import numpy as np
from simulation.mujoco.runtime.s_native_gait import SNativeGait,PROFILES
from simulation.mujoco.runtime.cad_physics import Simulation
from simulation.mujoco.runtime.virtual_robot import load_parameters,parse_args

HARMONICS=8

def export(output,report):
    plant=Simulation(load_parameters(parse_args([])))
    gait=SNativeGait(plant.model,plant.stand_target,PROFILES['s_native_v6_2_1'])
    table=[];errors=[]
    phase=2*np.pi*np.arange(64)/64
    basis=np.stack([np.ones(64)]+[f(h*phase) for h in range(1,HARMONICS+1) for f in (np.cos,np.sin)])
    for linear in np.arange(-10,11)/10:
        row=[]
        for yaw in np.arange(-5,6)/10:
            if abs(linear)+abs(yaw)<.1:
                values=np.zeros(64)
            else:
                gait.prepare_support(float(linear),float(yaw));values=gait.support_table
            spectrum=np.fft.rfft(values)/64
            coefficients=[spectrum[0].real]+[v for h in range(1,HARMONICS+1)
                for v in (2*spectrum[h].real,-2*spectrum[h].imag)]
            encoded=np.rint(np.asarray(coefficients)*1e6).astype(int)
            if np.max(abs(encoded))>32767:raise ValueError('Coefficient int16 overflow')
            errors.append(float(np.max(abs(encoded@basis/1e6-values))))
            row.append(encoded.tolist())
        table.append(row)
        print(f'V6.2.1 support: linear={linear:.1f}',flush=True)
    def init(value):
        return '{'+','.join(init(v) for v in value)+'}' if isinstance(value,list) else str(value)
    text='\n'.join(['/* Generated by export_s_native_v621_firmware.py; do not edit. */',
        '#ifndef S_NATIVE_V621_DATA_H','#define S_NATIVE_V621_DATA_H','#include <stdint.h>',
        f'#define SN_V621_HARMONICS {HARMONICS}',
        f'static const int16_t sn_v621_support_um[21][11][{1+2*HARMONICS}] = '+init(table)+';',
        '#endif',''])
    output.parent.mkdir(parents=True,exist_ok=True);output.write_text(text)
    result=dict(profile='s_native_v6_2_1',harmonics=HARMONICS,table_bytes=np.asarray(table).size*2,
        max_support_reconstruction_error_mm=max(errors)*1000,grid=[21,11],phases=64)
    report.parent.mkdir(parents=True,exist_ok=True);report.write_text(json.dumps(result,indent=2))
    print(json.dumps(result),flush=True)
    return result

if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output',type=Path,required=True);p.add_argument('--report',type=Path,required=True)
    a=p.parse_args();export(a.output,a.report)
