"""Export V6.1 CAD references and bounded support table for STM32."""
if __package__ in (None, ''):
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

import argparse
import json
from pathlib import Path
import numpy as np
from simulation.mujoco.runtime.cad_physics import Simulation
from simulation.mujoco.runtime.virtual_robot import load_parameters, parse_args
from simulation.mujoco.runtime.s_native_gait import SNativeGait, V61_PROFILE as PROFILE


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    plant = Simulation(load_parameters(parse_args([])))
    gait = SNativeGait(plant.model, plant.stand_target, PROFILE)
    kin = gait.kin
    kin.set_angles(np.zeros(12))
    sole = [kin.data.geom_xpos[f] + kin.data.geom_xmat[f].reshape(3, 3) @ kin.local_points[i]
            for i, f in enumerate(kin.feet)]
    table = []
    for linear in np.arange(-10, 11)/10:
        row = []
        for yaw in np.arange(-5, 6)/10:
            if abs(linear)+abs(yaw) < .1:
                values = np.zeros(64)
            else:
                gait.prepare_support(float(linear), float(yaw))
                values = gait.support_table
            row.append(np.rint(values*1e6).astype(int).tolist())
        table.append(row)
        print(f'Exported support linear={linear:.1f}', flush=True)
    if np.max(np.abs(table)) > 32767:
        raise ValueError('Support table overflows micrometre int16 encoding')
    values = dict(standing=np.asarray(plant.stand_target).reshape(4, 3).tolist(),
                  origin=gait.origin.tolist(), sole_zero=np.asarray(sole).tolist(),
                  lateral=gait.walking_lateral_offset.tolist(),
                  adduction=gait.normal_adduction.tolist(), support_um=table)
    def initializer(value, integer=False):
        if isinstance(value, list):
            return '{' + ','.join(initializer(v, integer) for v in value) + '}'
        return str(value) if integer else f'{float(value):.10e}f'
    lines = ['/* Generated by export_s_native_firmware.py from measured CAD; do not edit. */',
             '#ifndef S_NATIVE_DATA_H', '#define S_NATIVE_DATA_H', '#include <stdint.h>']
    for key, dims in [('standing','[4][3]'), ('origin','[4][3]'), ('sole_zero','[4][3]'),
                      ('lateral','[4]'), ('adduction','[4]'), ('support_um','[21][11][64]')]:
        integer = key == 'support_um'
        lines.append(f'static const {"int16_t" if integer else "float"} sn_{key}{dims} = '
                     + initializer(values[key], integer) + ';')
    lines += ['#endif', '']
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(lines), encoding='utf-8')


if __name__ == '__main__':
    main()
