import Foundation

enum RobotConnectionState: Equatable {
    case bluetoothUnavailable(String)
    case scanning
    case connecting
    case discoveringServices
    case ready
    case disconnected

    var title: String {
        switch self {
        case .bluetoothUnavailable(let reason): return reason
        case .scanning: return "로봇 검색 중"
        case .connecting: return "연결 중"
        case .discoveringServices: return "서비스 확인 중"
        case .ready: return "연결됨"
        case .disconnected: return "연결 안 됨"
        }
    }

    var isReady: Bool { self == .ready }
}

struct RobotRuntimeState: Equatable {
    var pose = "unknown"
    var poseErrorTicks = 0
    var torque = "unknown"
    var safety = "unknown"
    var balance = "unknown"
    var heading = "unknown"
    var revision = "unknown"
    var capabilities: Set<String> = []
    var simulationProfile = "legacy"
    var balanceTitle: String {
        switch balance {
        case "active": return "수평 보정 작동 중"
        case "full", "normal": return "수평 보정 켜짐"
        case "suspended": return "수평 보정 대기 · 자세/센서 확인"
        case "off": return "수평 보정 꺼짐"
        case "monitor": return "IMU 관측만 적용"
        default: return "균형 제어 확인 중"
        }
    }
    var supportsTrot5: Bool { capabilities.contains("trot5") }

    var poseTitle: String {
        switch pose {
        case "stand": return "Stand"
        case "stand11": return "Stand11"
        case "landing": return "Landing"
        case "custom": return "Custom"
        default: return "Unknown"
        }
    }
}

enum RobotDriveDirection: String {
    case forward
    case backward
    case left
    case right

    var title: String {
        switch self {
        case .forward: return "전진"
        case .backward: return "후진"
        case .left: return "좌회전"
        case .right: return "우회전"
        }
    }
}


enum RobotConnectionTarget: String, CaseIterable {
    case robot, simulatorBluetooth, simulator
    var isSimulator: Bool { self != .robot }
    var usesBluetooth: Bool { self != .simulator }
    var title: String {
        switch self {
        case .robot: return "실제 로봇 · BLE"
        case .simulatorBluetooth: return "가상 로봇 · BLE"
        case .simulator: return "가상 로봇 · TCP"
        }
    }
    var deviceName: String { self == .robot ? "SpotOMG-Bridge" : "SpotOMG-Sim" }
    var serviceID: String { self == .robot ? "6e400001-b5a3-f393-e0a9-e50e24dcca9e" : "6e400101-b5a3-f393-e0a9-e50e24dcca9e" }
    var receiveID: String { self == .robot ? "6e400002-b5a3-f393-e0a9-e50e24dcca9e" : "6e400102-b5a3-f393-e0a9-e50e24dcca9e" }
    var transmitID: String { self == .robot ? "6e400003-b5a3-f393-e0a9-e50e24dcca9e" : "6e400103-b5a3-f393-e0a9-e50e24dcca9e" }
    static func isSimulatorIdentity(_ line: String) -> Bool {
        let fields = Set(line.split(separator: " ").map(String.init))
        return line.hasPrefix("$SPOTBACKEND ") && fields.contains("backend=sim") && fields.contains("protocol=1")
    }
}


enum SimulatorGaitProfile: String, CaseIterable {
    case legacy, crawl, cruise, trot, highstep, lift, imu, level, level15, joint, jointfast, jointsport
    var title: String {
        switch self {
        case .legacy: return "기존 V16"
        case .crawl: return "크롤 · 한 발씩"
        case .cruise: return "크루즈 · 넓은 보폭"
        case .trot: return "빠른 트롯 · 실험"
        case .jointsport: return "J2 협응 · 스포츠"
        case .jointfast: return "J2 협응 · 빠르게"
        case .joint: return "J2·J3 협응 보행"
        case .level15: return "수평 + 발 들기 · 15mm"
        case .level: return "수평 우선 · Level"
        case .imu: return "IMU 적응 · 지지 다리 보정"
        case .lift: return "리프트 · 발 높이 20mm"
        case .highstep: return "높은 발 들기"
        }
    }
}

// BEGIN GENERATED GAIT SPEEDS
// Generated by tools/generate_gait_speed_labels.py. Nominal simulation, 60s full forward.
extension SimulatorGaitProfile {
    var benchmarkSpeedMetersPerSecond: Double? {
        switch self {
        case .legacy: return 0.047956415
        case .crawl: return 0.028477535
        case .cruise: return 0.212593697
        case .trot: return 0.173329346
        case .highstep: return 0.089345535
        case .lift: return 0.089345535
        case .imu: return 0.078093022
        case .level: return 0.099763812
        case .level15: return 0.076044601
        case .joint: return 0.085797550
        case .jointfast: return 0.105461897
        case .jointsport: return 0.138690490
        }
    }

    static func speedSuffix(_ speed: Double?) -> String {
        guard let speed, speed.isFinite, speed >= 0 else { return "(검증실패)" }
        return "(\(String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), speed))m/s)"
    }

    var titleWithSpeed: String { "\(title) \(Self.speedSuffix(benchmarkSpeedMetersPerSecond))" }
}
// END GENERATED GAIT SPEEDS
