"""User-visible gait names shared with the Apple controller; wire keys stay separate."""

PROFILE_TITLES = {'s_native_v6_2_7': 'V6.2.7 · 이른 접힘',
 's_native_v6_2_6': 'V6.2.6 · 연속 내딛기',
 's_native_v6_2_5': 'V6.2.5 · 신속 회수',
 's_native_v6_2_4': 'V6.2.4 · 도달 확인',
 's_native_v6_2_3': 'V6.2.3 · 확장',
 's_native_v6_2_2': 'V6.2.2 · 고속',
 's_native_v6_2_1': 'V6.2.1 · 연속 회수',
 's_native_v6_2': 'V6.2 · 뒤쪽 125mm',
 's_native_v6_1': 'V6.1 · 뒤쪽 65mm',
 's_native_v6': 'V6 · 수평 지지 교대',
 's_native_v5': 'V5 · FR 첫걸음',
 's_native_v4': 'V4 · J1 아래 착지',
 's_native_v3': 'V3 · 뒤로 밀기 60mm',
 's_native_v2': 'V2 · 연속 교대',
 's_native_v1': 'V1 · 대각선 동기',
 'attitudepd_v6': 'IMU 자세 안정화 V6 · 복귀 발들림 개선 · 실험',
 'attitudepd_v5': 'IMU 자세 안정화 V5 · 전진 추진 개선 · 실험',
 'attitudepd_v4': 'IMU 자세 안정화 V4 · 전후 공통 2단 보행 · 실험',
 'attitudepd_v3': 'IMU 자세 안정화 V3 · 보행 대기 Stand · 실험',
 'attitudepd_v2': 'IMU 자세 안정화 V2 · 앞발 들림 +4mm · 실험',
 'attitudepd': 'IMU 자세 안정화 · PD · 실험',
 'centerpivot': '몸체 중심 회전 보정 · 실험',
 'arcsupport': '원호 턴 · 지지 전환 보정 · 실험',
 'arcturn': '원호 턴 · 실물 시험',
 'cushion_diagonal_sync_wide80': '대각선 · 넓은 보폭 80mm',
 'cushion_v2_push': 'V2 · 추진 타이밍 · 실험',
 'cushion_support_shift_v2': 'V2 · J1 고정 · 실험',
 'cushion_support_shift': '큰 스텝 · 지지 전환 보정 · 실험',
 'cushion_forward': '큰 전진 스텝 · 실험',
 'cushion_reach': '쿠션 · 어깨 앞 착지',
 'cushion_j2lift': '쿠션 · J2 높이 들기',
 'cushion_wbc': '전신 수평 · 아치 보행 · 실험',
 'legacy': '기존 V16',
 'crawl': '크롤 · 한 발씩',
 'cruise': '크루즈 · 넓은 보폭',
 'trot': '빠른 트롯 · 실험',
 'jointsport': 'J2 협응 · 스포츠',
 'jointfast': 'J2 협응 · 빠르게',
 'joint': 'J2·J3 협응 보행',
 'level15': '수평 + 발 들기 · 15mm',
 'level': '수평 우선 · Level',
 'imu': 'IMU 적응 · 지지 다리 보정',
 'lift': '리프트 · 발 높이 20mm',
 'highstep': '높은 발 들기'}

def profile_title(key):
    return PROFILE_TITLES.get(key, key)
