import Foundation

@main
struct CheckStowControls {
    static func main() {
        var sent = [String]()
        let manager = RobotBluetoothManager(commandWriter: { sent.append(String(decoding: $0, as: UTF8.self)) })
        manager.receiveConsoleText("$SPOTSTATE pose=stow safety=ok caps=simstow\r\n")
        assert(manager.stowControlLocked)
        sent.removeAll()
        for command: RobotCommand in [.stand, .stand11, .stow, .recover, .relax,
            .headingHold(true), .simulatorBalance(true), .raw("stand"), .raw("relax"),
            .drive(linearPerMille: 1000, yawPerMille: 0, sequence: 1)] {
            assert(!manager.permitsCommand(command))
            manager.send(command)
        }
        manager.updateDrive(x: 0, y: 1)
        assert(sent.isEmpty)
        manager.send(.landing)
        assert(sent == ["landing\n"])
        assert(manager.postureInProgress == "landing" && manager.motionControlsLocked)
        manager.send(.landing)
        manager.send(.stand)
        manager.updateDrive(x: 0, y: 1)
        assert(sent == ["landing\n"], "Lock immediately and prevent duplicate commands")
        manager.receiveConsoleText("$SPOTSTATE pose=custom safety=ok caps=simstow\r\n")
        assert(manager.stowControlLocked, "Keep lock during unfolding")
        manager.receiveConsoleText("OK landing\r\n")
        assert(!manager.stowControlLocked && manager.runtimeState.pose == "landing")
        assert(manager.permitsCommand(.stand))
        sent.removeAll()
        manager.send(.stand)
        assert(manager.motionControlsLocked)
        manager.send(.stand11)
        assert(sent == ["stand\n"])
        manager.receiveConsoleText("$SPOTSTATE pose=landing safety=ok caps=simstow\r\n")
        assert(manager.postureInProgress == "stand", "Old snapshots must not release the lock")
        manager.receiveConsoleText("OK stand\r\n")
        assert(!manager.motionControlsLocked)
        manager.send(.stand11)
        assert(manager.motionControlsLocked)
        manager.receiveConsoleText("ERROR: rejected\r\n")
        assert(!manager.motionControlsLocked)
        manager.receiveConsoleText("OK stow\r\n")
        assert(manager.stowControlLocked && manager.runtimeState.pose == "stow")
        assert(manager.permitsCommand(.syncState))
        assert(manager.permitsCommand(.hold))
        sent.removeAll()
        manager.send(.hold)
        assert(sent == ["\u{03}"], "Stop must use the priority interrupt")
        assert(manager.stopRequested)
        assert(!manager.permitsCommand(.landing) && !manager.permitsCommand(.stow))
        manager.receiveConsoleText("STOPPED: interrupt\r\n")
        assert(!manager.stopRequested)
        assert(manager.runtimeState.pose == "stow-paused")
        assert(manager.permitsCommand(.landing) && manager.permitsCommand(.stow))
        assert(!manager.permitsCommand(.stand))
        manager.send(.landing)
        assert(!manager.permitsCommand(.stow), "Lock again immediately after resume")
        manager.receiveConsoleText("OK landing\r\n")
        manager.send(.stand)
        sent.removeAll()
        manager.send(.hold)
        assert(sent == ["\u{03}"])
        assert(manager.postureInProgress == "stand", "Wait for stop acknowledgement")
        manager.receiveConsoleText("STOPPED: interrupt\r\n")
        assert(manager.postureInProgress == nil)
        manager.disconnect()
        assert(!manager.stowControlLocked)
        print("Stow UI/transport interlock checks passed")
    }
}
