import Foundation
@main struct CheckRemote {
 static func main() {
  var sent=[String]()
  let m=RobotBluetoothManager(commandWriter: { sent.append(String(decoding:$0,as:UTF8.self)) })
  m.send(.relax)
  assert(sent == ["landing\n"])
  m.receiveConsoleText("ERROR: motion aborted\r\n# ")
  assert(!sent.contains("relax\n"))
  m.send(.relax)
  m.receiveConsoleText("OK landing\r\n# ")
  assert(sent.last == "relax\n")
  sent.removeAll()
  m.send(.stand)
  let now=Date().timeIntervalSince1970
  m.beginRemoteRequest(AppRemoteRequest(id:UUID().uuidString,action:"disconnect",issuedAt:now,expiresAt:now+30,target:nil))
  assert(m.state.isReady && m.remotePending != nil)
  assert(sent.last == "\u{03}")
  m.send(.stand11)
  assert(sent.last == "\u{03}")
  m.receiveConsoleText("ERROR: motion aborted\r\n# ")
  m.advanceRemoteRequest()
  assert(!m.state.isReady && m.remotePending == nil)
  print("Remote disconnect and Landing-before-Relax checks passed")
  let folder=FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
  try! FileManager.default.createDirectory(at:folder,withIntermediateDirectories:true)
  defer { try? FileManager.default.removeItem(at:folder) }
  let mailbox=RobotBluetoothManager(commandWriter:{ _ in },remoteMailbox:folder)
  let id=UUID().uuidString
  let request=folder.appendingPathComponent("request.json")
  try! JSONSerialization.data(withJSONObject:["id":id,"action":"status","issuedAt":now,"expiresAt":now+30]).write(to:request)
  mailbox.pollRemoteControl()
  assert(FileManager.default.fileExists(atPath:request.path))
  let response=folder.appendingPathComponent("response-\(id).json")
  let first=try! Data(contentsOf:response)
  mailbox.pollRemoteControl()
  assert(try! Data(contentsOf:response)==first)
  assert(SimulatorGaitProfile.arcsupport.titleWithSpeed.contains("검증실패"))
  assert(!SimulatorGaitProfile.arcsupport.isSupported(capabilities:["gaitprofiles"]))
  assert(SimulatorGaitProfile.arcsupport.isSupported(capabilities:["gaitprofiles","arcsupport"]))
  sent.removeAll()
  let guarded=RobotBluetoothManager(commandWriter:{sent.append(String(decoding:$0,as:UTF8.self))})
  guarded.receiveConsoleText("$SPOTSTATE pose=stand rev=shared-locomotion-v41 caps=gaitprofiles\r\n")
  guarded.send(.simulatorProfile(.arcsupport))
  assert(!sent.contains("gaitprofile arcsupport\n"))
  guarded.receiveConsoleText("$SPOTSTATE pose=stand rev=shared-locomotion-v43 caps=gaitprofiles,arcsupport\r\n")
  guarded.send(.simulatorProfile(.arcsupport))
  assert(sent.contains("gaitprofile arcsupport\n"))
  assert(SimulatorGaitProfile.centerpivot.titleWithSpeed.contains("검증실패"))
  assert(!SimulatorGaitProfile.centerpivot.simulatorOnly)
  assert(!SimulatorGaitProfile.centerpivot.isSupported(capabilities:["gaitprofiles"]))
  assert(SimulatorGaitProfile.centerpivot.isSupported(capabilities:["gaitprofiles","centerpivot"]))
  sent.removeAll()
  guarded.send(.simulatorProfile(.centerpivot))
  assert(!sent.contains("gaitprofile centerpivot\n"))
  guarded.receiveConsoleText("$SPOTSTATE pose=stand rev=shared-locomotion-v48 caps=gaitprofiles,centerpivot\r\n")
  guarded.send(.simulatorProfile(.centerpivot))
  assert(sent.contains("gaitprofile centerpivot\n"))
  var defaults=[String]()
  let auto=RobotBluetoothManager(commandWriter:{defaults.append(String(decoding:$0,as:UTF8.self))})
  let idle="$SPOTSTATE pose=landing torque=off safety=ok rev=shared-locomotion-v48 caps=gaitprofiles,centerpivot profile=cruise\r\n"
  auto.receiveConsoleText(idle)
  assert(defaults.filter{$0=="gaitprofile centerpivot\n"}.count==1)
  // Display stays truthful until the firmware confirms the selection.
  assert(auto.runtimeState.simulationProfile=="cruise")
  auto.receiveConsoleText(idle)
  assert(defaults.filter{$0=="gaitprofile centerpivot\n"}.count==1)
  auto.receiveConsoleText(idle.replacingOccurrences(of:"profile=cruise",with:"profile=centerpivot"))
  assert(auto.runtimeState.simulationProfile=="centerpivot")
  auto.send(.simulatorProfile(.cruise))
  auto.receiveConsoleText(idle)
  assert(defaults.filter{$0=="gaitprofile centerpivot\n"}.count==1)
  var deferred=[String]()
  let busy=RobotBluetoothManager(commandWriter:{deferred.append(String(decoding:$0,as:UTF8.self))})
  busy.send(.stand)
  busy.receiveConsoleText(idle)
  assert(!deferred.contains("gaitprofile centerpivot\n"))
  busy.receiveConsoleText("OK stand\r\n# ")
  busy.receiveConsoleText(idle.replacingOccurrences(of:"pose=landing",with:"pose=stand"))
  assert(deferred.contains("gaitprofile centerpivot\n"))
  print("Mailbox copy-verification race, request deduplication, and V43 capability checks passed")
 }
}
