"""Generate every app policy's reference speed from completed benchmarks."""
import argparse,hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TARGET=ROOT/'apps/ios/SpotOMGController/SpotOMGController/Models/ConnectionState.swift'
BEGIN='// BEGIN GENERATED GAIT SPEEDS'
END='// END GENERATED GAIT SPEEDS'

def render():
    manifest=ROOT/'config/locomotion_profiles.json'
    data=json.loads((ROOT/'config/locomotion_speed_benchmarks.json').read_text())
    assert data['manifest_sha256']==hashlib.sha256(manifest.read_bytes()).hexdigest(),'Run speed benchmark after changing profiles'
    assert data['heading_controller_sha256']==hashlib.sha256((ROOT/'firmware/stm32-learning/Inc/heading_control.h').read_bytes()).hexdigest(),'Run speed benchmark after changing heading control'
    names=('legacy',*json.loads(manifest.read_text())['profiles'])
    assert set(data['profiles'])==set(names),'Incomplete speed benchmark'
    lines=[BEGIN,'// Generated by tools/generate_gait_speed_labels.py. Nominal simulation, 60s full forward.','extension SimulatorGaitProfile {','    var benchmarkSpeedMetersPerSecond: Double? {','        switch self {']
    for name in names:
        row=data['profiles'][name];value=row['speed_m_s']
        if row['passed']:assert value is not None and math.isfinite(value) and value>=0
        else:assert value is None
        lines.append(f'        case .{name}: return '+(format(value,'.9f') if row['passed'] else 'nil'))
    lines += ['        }','    }','',
        '    static func speedSuffix(_ speed: Double?) -> String {',
        '        guard let speed, speed.isFinite, speed >= 0 else { return "(검증실패)" }',
        '        return "(\\(String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), speed))m/s)"',
        '    }','',
        '    var titleWithSpeed: String { "\\(title) \\(Self.speedSuffix(benchmarkSpeedMetersPerSecond))" }','}',END]
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    source=TARGET.read_text();block=render()
    if BEGIN in source:
        a=source.index(BEGIN);b=source.index(END,a)+len(END)
        updated=source[:a]+block.rstrip('\n')+source[b:]
    else:updated=source+'\n'+block
    if args.check:assert source==updated,'Regenerate gait speed labels'
    else:TARGET.write_text(updated)
