"""Generate a named-field C default from the complete, strictly checked JSON."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# (minimum, maximum, minimum_inclusive, integer). Field names, not tuple order,
# define the serialization contract and the generated C designated initializer.
FIELDS = {
    'target_roll_rad': (-.35, .35, True, False),
    'target_pitch_rad': (-.35, .35, True, False),
    'kp_roll': (0., 2., True, False),
    'kp_pitch': (0., 2., True, False),
    'kd_roll_s': (0., .2, True, False),
    'kd_pitch_s': (0., .2, True, False),
    'angle_alpha': (0., 1., True, False),
    'gyro_alpha': (0., 1., True, False),
    'max_roll_rad': (0., .2, False, False),
    'max_pitch_rad': (0., .2, False, False),
    'max_foot_offset_m': (0., .005, False, False),
    'max_error_rad': (0., .6, False, False),
    'max_gyro_rad_s': (0., 10., False, False),
    'timeout_ms': (1, 1000, True, True),
    'slew_rad_s': (0., 2., False, False),
    'stance_transition_s': (0., .25, False, False),
}


def validate_config(config):
    if not isinstance(config, dict):
        raise ValueError('Configuration must be an object')
    expected = set(FIELDS) | {'schema_version'}
    if set(config) != expected:
        raise ValueError(f'Configuration fields differ: missing={sorted(expected-set(config))}, '
                         f'unknown={sorted(set(config)-expected)}')
    if type(config['schema_version']) is not int or config['schema_version'] != 1:
        raise ValueError('schema_version must be integer 1')
    for key, (minimum, maximum, inclusive, integer) in FIELDS.items():
        value = config[key]
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f'{key} must be numeric')
        if integer and type(value) is not int:
            raise ValueError(f'{key} must be an integer')
        if not math.isfinite(value) or value > maximum or (value < minimum if inclusive else value <= minimum):
            raise ValueError(f'{key} is outside its permitted range')
        if key in ('angle_alpha', 'gyro_alpha') and value >= 1:
            raise ValueError(f'{key} is previous-value weight and must be less than 1')
    return dict(config)


def load_config(path):
    def unique_object(pairs):
        result = {}
        for key, value in pairs:
            if key in result:
                raise ValueError(f'Duplicate configuration field: {key}')
            result[key] = value
        return result
    return validate_config(json.loads(Path(path).read_text(), object_pairs_hook=unique_object))


def render(config):
    config = validate_config(config)
    canonical = json.dumps(config, sort_keys=True, separators=(',', ':'), allow_nan=False)
    lines = ['/* Generated by tools/generate_body_stabilization_config.py. Do not edit. */',
             '#ifndef BODY_STABILIZATION_CONFIG_H', '#define BODY_STABILIZATION_CONFIG_H',
             '#include "body_stabilizer.h"',
             '#define BODY_STABILIZATION_CONFIG_SHA256 "'+hashlib.sha256(canonical.encode()).hexdigest()+'"',
             'static const BodyStabilizerConfig BODY_STABILIZATION_DEFAULT_CONFIG = {']
    for name, (_, _, _, integer) in FIELDS.items():
        value = str(config[name])+'U' if integer else format(config[name], '.10g')
        if not integer:
            if not any(char in value for char in '.eE'):
                value += '.0'
            value += 'f'
        lines.append(f'    .{name} = {value},')
    return '\n'.join(lines + ['};',
        'static inline BodyStabilizerConfig body_stabilizer_default_config(void) {',
        '    return BODY_STABILIZATION_DEFAULT_CONFIG;', '}', '#endif', ''])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', type=Path, default=ROOT/'config/body_stabilization.json')
    parser.add_argument('--output', type=Path, default=ROOT/'firmware/stm32-learning/Inc/body_stabilization_config.h')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        config = load_config(args.config)
        generated = render(config)
        if args.check:
            if args.output.read_text() != generated:
                parser.error('Generated header differs; run tools/generate_body_stabilization_config.py')
        else:
            args.output.write_text(generated)
    except (ValueError, OSError) as error:
        parser.error(str(error))


if __name__ == '__main__':
    main()
