"""Generate every app policy's reference speed from completed benchmarks."""
import argparse,hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TARGET=ROOT/'apps/ios/SpotOMGController/SpotOMGController/Models/ConnectionState.swift'
BEGIN='// BEGIN GENERATED GAIT SPEEDS'
END='// END GENERATED GAIT SPEEDS'

def render():
    manifest=ROOT/'config/locomotion_profiles.json'
    data=json.loads((ROOT/'config/locomotion_speed_benchmarks.json').read_text())
    current=json.loads(manifest.read_text())
    if data['manifest_sha256']!=hashlib.sha256(manifest.read_bytes()).hexdigest():
        reference=ROOT/'config/locomotion_speed_reference_manifest.json'
        assert hashlib.sha256(reference.read_bytes()).hexdigest()==data['manifest_sha256'],'Benchmark provenance mismatch'
        previous=json.loads(reference.read_text())
        assert current['default']==previous['default']
        assert all(current['profiles'].get(name)==cfg for name,cfg in previous['profiles'].items()),'Changed policy needs a new benchmark'
        assert all(cfg.get('experimental',False) for name,cfg in current['profiles'].items() if name not in previous['profiles']),'New policy needs a benchmark or experimental flag'
    assert data['heading_controller_sha256']==hashlib.sha256((ROOT/'firmware/stm32-learning/Inc/heading_control.h').read_bytes()).hexdigest(),'Run speed benchmark after changing heading control'
    names=('legacy',*json.loads(manifest.read_text())['profiles'])
    assert set(data['profiles'])<=set(names),'Unknown benchmark profile'
    assert all(name!='legacy' and current['profiles'][name].get('experimental',False) for name in set(names)-set(data['profiles'])),'Missing non-experimental benchmark'
    lines=[BEGIN,'// Generated by tools/generate_gait_speed_labels.py. Nominal simulation, 60s full forward.','extension SimulatorGaitProfile {','    var benchmarkSpeedMetersPerSecond: Double? {','        switch self {']
    for name in names:
        row=data['profiles'].get(name,dict(passed=False,speed_m_s=None));value=row['speed_m_s']
        if row['passed']:assert value is not None and math.isfinite(value) and value>=0
        else:assert value is None
        lines.append(f'        case .{name}: return '+(format(value,'.9f') if row['passed'] else 'nil'))
    experiments=json.loads((ROOT/'simulation/mujoco/upright_profiles.json').read_text())['profiles']
    cushion=json.loads((ROOT/'simulation/mujoco/foot_cushion_d37p3_l27mm.json').read_text())
    for name,filename in [('cushion_reach','reach373-validation.json'),('cushion_j2lift','j2lift-validation.json'),('cushion_forward','forward-reach-validation.json')]:
        rows=json.loads((ROOT/'artifacts/upright/2026-09-11/cushion'/filename).read_text())
        row=next(r for r in rows if r.get('case')=='forward')
        valid=row['safety']=='ok' and row.get('quality_passed',True) and row['profile']['params']==experiments[name]['params'] and row['cushion']==cushion
        lines.append(f'        case .{name}: return '+(format(row['speed_m_s'],'.9f') if valid else 'nil'))
    lines.append('        case .cushion_wbc: return nil')
    # V2 remains experimental until the complete physical acceptance suite passes.
    lines.append('        case .cushion_support_shift_v2: return nil')
    lines.append('        case .cushion_v2_push: return nil')
    lines.append('        case .cushion_diagonal_sync_wide80: return nil')
    support_path=ROOT/'artifacts/upright/2026-09-11/cushion/support-shift-validation.json'
    support_rows=json.loads(support_path.read_text()) if support_path.exists() else []
    support=next((r for r in support_rows if r.get('case')=='forward'),{})
    required={'forward','com_offset','servo_delay','motor_loss','cushion_soft_slippery','imu_delay','forward_stop'}
    valid=(set(r['case'] for r in support_rows)==required and support.get('suite_passed',False)
           and all(r.get('quality_passed',False) and all(r.get('gates',{}).values()) for r in support_rows)
           and support.get('profile')==experiments['cushion_support_shift'] and support.get('cushion')==cushion
           and bool(support.get('controller_sha256'))
           and all(hashlib.sha256((ROOT/'simulation/mujoco'/name).read_bytes()).hexdigest()==digest
                   for name,digest in support.get('controller_sha256',{}).items()))
    lines.append('        case .cushion_support_shift: return '+(format(support['speed_m_s'],'.9f') if valid else 'nil'))
    lines += ['        }','    }','',
        '    static func speedSuffix(_ speed: Double?) -> String {',
        '        guard let speed, speed.isFinite, speed >= 0 else { return "(검증실패)" }',
        '        return "(\\(String(format: "%.3f", locale: Locale(identifier: "en_US_POSIX"), speed))m/s)"',
        '    }','',
        '    var titleWithSpeed: String { "\\(title) \\(Self.speedSuffix(benchmarkSpeedMetersPerSecond))" }','}',END]
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    source=TARGET.read_text();block=render()
    if BEGIN in source:
        a=source.index(BEGIN);b=source.index(END,a)+len(END)
        updated=source[:a]+block.rstrip('\n')+source[b:]
    else:updated=source+'\n'+block
    if args.check:assert source==updated,'Regenerate gait speed labels'
    else:TARGET.write_text(updated)
