"""Generate embedded profile constants from the single deployment manifest."""
import json
import hashlib
from pathlib import Path
import argparse
ROOT=Path(__file__).resolve().parents[1]
def render():
 manifest=json.loads((ROOT/'config/locomotion_profiles.json').read_text())
 p=manifest['profiles']
 names=('legacy',*p)
 rows=['/* Generated by tools/generate_locomotion_profiles.py. Do not edit. */',
       '#ifndef LOCOMOTION_PROFILES_H','#define LOCOMOTION_PROFILES_H',
       '#define LOCOMOTION_MANIFEST_SHA256 "'+hashlib.sha256((ROOT/'config/locomotion_profiles.json').read_bytes()).hexdigest()+'"',
       '#define LOCOMOTION_PROFILE_COUNT '+str(len(names)),
       '#define LOCOMOTION_DEFAULT_PROFILE '+str(names.index(manifest['default'])),
       'static const char *const locomotion_names[] = {'+','.join(json.dumps(n) for n in names)+'};',
       'static const float locomotion_parameters['+str(len(names))+'][2][7] = {', '  {{0},{0}},']
 for name in p:
  forward=p[name]['params'];base=p[name].get('turn_reverse_params',forward)
  fmt=lambda a:'{'+','.join(format(v,'.10g')+('f' if any(c in format(v,'.10g') for c in '.eE') else '.0f') for v in a)+'}'
  rows.append('  {'+fmt(forward)+','+fmt(base)+'},')
 rows+=['};','static const float locomotion_joint_lead_s[LOCOMOTION_PROFILE_COUNT][3] = {','  {0,0,0},']
 for name in p:
  lead=p[name].get('joint_lead_s',[0,0,0])
  assert len(lead)==3 and all(0<=v<=.1 for v in lead)
  rows.append('  '+fmt(lead)+',')
 rows+=['};','static const float locomotion_turn_lift_m[LOCOMOTION_PROFILE_COUNT] = {', '  0.0f,']
 for name in p:
  lift=p[name].get('turn_lift_m',0.)
  assert 0<=lift<=.04
  rows.append('  '+format(lift,'.10f')+'f,')
 rows+=['};','static const float locomotion_turn_posture_m[LOCOMOTION_PROFILE_COUNT][2] = {', '  {0.0f,0.0f},']
 for name in p:
  posture=p[name].get('turn_posture_m',[0,0])
  assert len(posture)==2 and (posture==[0,0] or (.18<=posture[0]<=.25 and abs(posture[1])<=.05))
  rows.append('  '+fmt(posture)+',')
 return '\n'.join(rows+['};','#endif',''])
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 path=ROOT/'firmware/stm32-learning/Inc/locomotion_profiles.h'
 if args.check:assert path.read_text()==render(),'Run profile generator'
 else:path.write_text(render())
